### PR TITLE
Updating Screenshots

### PR DESCRIPTION
**Pull request by Abby-Wheelis**
Starting this PR to replace some of the outdated screenshots in parallel with the Laos work

### CODE REVIEW

**Comment by Abby-Wheelis** [comment]
Now all four screenshots have been updated, but I need to test to make sure the image sizes still work (particularly with the new public dashboard layout being less compact)

**Comment by Abby-Wheelis** [comment]
Screenshot 2024-07-31 at 2 51 41 PM

The phone screenshot looks great, but it is hard to read the public dashboard ...

**Comment by phothisath5665** [comment]
can we expand a new picture in the public dashboard to be more readable?
also, can we include "use it to estimate the individual transportation carbon footprint.... the dashboard also shows the individual and group average of the carbon footprint"

**Comment by Abby-Wheelis** [comment]
>can we expand a new picture in the public dashboard to be more readable?

Do you mean make the size of the image larger? I'm not sure if we can, since we are limited by the layout of the webpage. I could try making the phone screenshot smaller and the dashboard screenshot larger.

>also, can we include "use it to estimate the individual transportation carbon footprint.... the dashboard also shows the individual and group average of the carbon footprint"

We could say "uses it to estimate your individual transportation carbon footprint and compare it against US 2030 and 2050 carbon-reduction goals **_and your group's average._** It also computes and publishes aggregate metrics around mode share and distance traveled."

The energy/emission graph is not always on the dashboard, that only applies to "program" types, not "study" types. I might argue that I should update the screenshot to be of a "study" and not a "program" to prevent confusion

**Comment by phothisath5665** [comment]
Oki I do agree with you on the public dashboard :)

Regarding to our videos that we made last time. I do not know how to add a music in the video. Do you have any advice about that?

**Comment by Abby-Wheelis** [comment]
>Regarding to our videos that we made last time. I do not know how to add a music in the video. Do you have any advice about that?

The very limited video editing that I have done has been an iMovie, which is available on apple computers (and phones, I think). I'm not sure that we need music, if someone is watching it from scanning a flyer, they are likely in public and would not want to play sound from their phone. If you play the recording in a meeting, you could talk over it to explain how to install. If you feel strongly about adding music, maybe the NREL library subscribes to a free software you could use?

**Comment by Abby-Wheelis** [comment]
Old:
Screenshot 2024-10-17 at 2 44 48 PM

New:
Screenshot 2024-10-17 at 2 43 52 PM

**Review by shankari — APPROVED** [review]

**Pull request merged**
